set(RT_ASIO_SDK_URL "https://download.steinberg.net/sdk_downloads/ASIO-SDK_2.3.4_2025-10-15.zip")
set(RT_ASIO_SDK_SHA256 "d5ebf0c20dd2c5f43771fd0c1418f4b361bf52434ee670097cfa6b3a335e2eca")

# Sets <out> to the ASIOSDK folder: RT_ASIO_SDK_DIR if given, else the pinned download.
function(rt_resolve_asio_sdk out)
    if(RT_ASIO_SDK_DIR)
        set(dir "${RT_ASIO_SDK_DIR}")
    else()
        set(root "${CMAKE_BINARY_DIR}/_deps/asiosdk-2.3.4")
        set(zip  "${CMAKE_BINARY_DIR}/_deps/asiosdk-2.3.4.zip")
        set(dir  "${root}/ASIOSDK")
        if(NOT EXISTS "${dir}/common/iasiodrv.h")
            file(DOWNLOAD "${RT_ASIO_SDK_URL}" "${zip}"
                 EXPECTED_HASH SHA256=${RT_ASIO_SDK_SHA256} TLS_VERIFY ON STATUS status)
            list(GET status 0 code)
            if(NOT code EQUAL 0)
                list(GET status 1 reason)
                message(FATAL_ERROR "rt_audio: could not download the ASIO SDK from ${RT_ASIO_SDK_URL}: ${reason}")
            endif()
            file(ARCHIVE_EXTRACT INPUT "${zip}" DESTINATION "${root}")
        endif()
    endif()
    if(NOT EXISTS "${dir}/common/iasiodrv.h")
        message(FATAL_ERROR "rt_audio: ${dir}/common/iasiodrv.h not found. RT_ASIO_SDK_DIR must point to the ASIOSDK folder.")
    endif()
    set(${out} "${dir}" PARENT_SCOPE)
endfunction()
